apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tapdemo
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tapdemo
spec:
  source:
    git:
      url: https://github.com/desotech-it/tapdemo.git
      ref:
        branch: main
